services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pwd4postgres!
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-compose-db-init.sql:/docker-entrypoint-initdb.d/docker-compose-db-init.sql:ro

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready"]
#      interval: 1s
#      timeout: 5s
#      retries: 10

volumes:
  pgdata:
